# Generated by Django 4.2.7 on 2023-11-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freebie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('percentage_off', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('amount_off', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('city', models.TextField(choices=[('BERLIN', 'Berlin'), ('BUENOS_AIRES', 'Buenos Aires'), ('HYDERABAD', 'Hyderabad'), ('LONDON', 'London'), ('SAN_FRANCISCO', 'San Francisco'), ('SEOUL', 'Seoul'), ('TAIPEI', 'Taipei')])),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
